- name: Setup Kubernetes Control Plane
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Enable memory cgroup
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        line: "cgroup_enable=memory cgroup_memory=1"
        state: present
        regexp: "cgroup_enable=memory cgroup_memory=1"
      register: cmdline_update
      notify: reboot

    - name: Ensure K3s configuration directory exists
      ansible.builtin.file:
        name: /etc/rancher/k3s
        state: directory

    - name: Copy K3s configuration
      ansible.builtin.copy:
        src: k3s-config.yaml
        dest: /etc/rancher/k3s/config.yaml

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        msg: "Rebooting"
        timeout: 300
