- name: Setup Kubernetes Control Plane
  hosts: all
  become: true

  tasks:
    # Steps below are taken from: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
    - name: Update packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present
        update_cache: true

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/kubernetes-release-key
        mode: '0644'
        when: not ansible.builtin.file(path='/etc/apt/keyrings/kubernetes-apt-keyring.gpg').stat.exists

    - name: Convert GPG key to armored format
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release-key
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Remove temporary key file
      ansible.builtin.file:
        path: /tmp/kubernetes-release-key
        state: absent

    - name: Add Kubernetes APT Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present

    - name: Install Kubernetes Tools
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true
        install_recommends: false

    - name: Enable kubelet service
      ansible.builtin.service:
        name: kubelet
        state: started

    - name: Create kubeadm configuration file from template
      ansible.builtin.template:
        src: "kubeadm-config.yaml.j2"
        dest: /etc/kubernetes/kubeadm-config.yaml
        owner: "root"
        group: "root"
        mode: '0644'
