- name: Setup Kubernetes Control Plane
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Enable memory cgroup
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        line: "cgroup_enable=memory cgroup_memory=1"
        state: present
        regexp: "cgroup_enable=memory cgroup_memory=1"
      register: cmdline_update
      notify: reboot

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        msg: "Rebooting"
        timeout: 300
